buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath 'com.palantir.baseline:gradle-baseline-java:6.72.0'
        classpath 'com.palantir.gradle.consistentversions:gradle-consistent-versions:3.7.0'
        classpath 'com.palantir.gradle.externalpublish:gradle-external-publish-plugin:1.27.0'
        classpath 'com.palantir.gradle.failure-reports:gradle-failure-reports:1.18.0'
        classpath 'com.palantir.gradle.gitversion:gradle-git-version:4.2.0'
        classpath 'com.palantir.gradle.idea-configuration:gradle-idea-configuration:0.8.0'
        classpath 'com.palantir.gradle.jdks:gradle-jdks:0.69.0'
        classpath 'com.palantir.gradle.jdkslatest:gradle-jdks-latest:0.24.0'
        classpath 'com.palantir.jakartapackagealignment:jakarta-package-alignment:0.6.0'
        classpath 'com.palantir.javaformat:gradle-palantir-java-format:2.82.0'
        classpath 'com.palantir.suppressible-error-prone:gradle-suppressible-error-prone:2.26.0'
    }
}

apply plugin: 'java-library'
apply plugin: 'com.palantir.baseline'
apply plugin: 'com.palantir.baseline-java-versions'
apply plugin: 'com.palantir.baseline-class-uniqueness'
apply plugin: 'com.palantir.baseline-exact-dependencies'
apply plugin: 'com.palantir.baseline-null-away'
apply plugin: 'com.palantir.consistent-versions'
apply plugin: 'com.palantir.external-publish'
apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'com.palantir.failure-reports'
apply plugin: 'com.palantir.git-version'
apply plugin: 'com.palantir.jakarta-package-alignment'
apply plugin: 'com.palantir.java-format'
apply plugin: 'com.palantir.jdks'
apply plugin: 'com.palantir.jdks.latest'

group 'com.palantir.ri'
version gitVersion()

repositories {
    mavenCentral() { metadataSources { mavenPom(); ignoreGradleMetadataRedirection() } }
}

sourceSets {
    jmh
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-annotations'
    implementation 'com.google.errorprone:error_prone_annotations'
    implementation 'com.palantir.safe-logging:safe-logging'
    implementation 'com.palantir.safe-logging:preconditions'
    implementation 'org.jspecify:jspecify'

    testImplementation 'com.fasterxml.jackson.core:jackson-databind'
    testImplementation 'com.palantir.safe-logging:preconditions-assertj'
    testImplementation 'net.jqwik:jqwik-api'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testImplementation 'org.junit.jupiter:junit-jupiter-params'

    testRuntimeOnly 'net.jqwik:jqwik-engine'

    jmhAnnotationProcessor 'org.openjdk.jmh:jmh-generator-annprocess'

    jmhImplementation project(':')
    jmhImplementation 'org.openjdk.jmh:jmh-core'
}

tasks.register('benchmark', JavaExec) {
    classpath = sourceSets.jmh.runtimeClasspath
    mainClass = 'org.openjdk.jmh.Main'

    if (project.hasProperty('jmh')) {
        args(project.property('jmh').split(' '))
    }
}

tasks.named('check') { dependsOn 'javadoc', 'checkUnusedDependencies', 'checkImplicitDependencies' }

javaVersions {
    libraryTarget = 17
    runtime = 25
}

jdks {
    daemonTarget = 21
}
